name: tsgxr

channels:
  - conda-forge # get things from conda-forge first
  - defaults

dependencies:
  - python<=3.11
  - numpy
  - pandas
  - matplotlib
  - xarray>=2024.10
  - zarr
  - dask
  - distributed
  - tqdm
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  - typer
  - ruff
  - pytest
  - pytest-cov
  - versioneer
  - jupyterlab-spellchecker
  - jupyterlab_code_formatter
  - twine
  - pip:
      - -e .
# Create ################################################
# conda env create -f environment.yml
# python -m ipykernel install --user --name tsgxr

# ACTIVATE ##############################################
# conda activate tsgxr

# REMOVE ################################################
# conda deactivate tsgxr
# conda env remove -n tsgxr
# jupyter kernelspec uninstall tsgxr
