name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d
        with:
            version: "latest"
            activate-environment: true
            python-version: 3.13
            enable-cache: true
            cache-dependency-glob: |
              **/pyproject.toml

      - name: Sync (no dev deps)
        run: uv sync --no-default-groups

      - name: Build wheel and sdist
        run: uv build --no-sources

      - name: Publish to pypi
        run: uv publish